version: '3.7'

services:
  redis:
    image: "redis:alpine"
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    command: python manage.py runserver 0.0.0.0:8008
    volumes:
      - ./:/src
    ports:
      - 8008:8008
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
